// Flash card content, in English (en) and Bahasa Indonesia (id).
//
// Card fields:
//   id      unique within its category; also the sound file name
//   emoji   the picture (or any short text, e.g. "3" or "A")
//   swatch  optional CSS color: draws a big colored circle instead of the emoji
//   extra   optional small line under the picture (e.g. "⭐⭐⭐" for numbers)
//   name    { en, id } — shown written and spoken aloud
//   audio   optional recording path, e.g. 'vehicles/siren' (lets several cards
//           share one file). Otherwise the card plays sounds/<category>/<id>.mp3
//           if that recording exists (listed in sounds/index.js).

const card = (id, emoji, en, idn) => ({ id, emoji, name: { en, id: idn } });

const NUMBERS_EN = ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'];
const NUMBERS_ID = ['Satu', 'Dua', 'Tiga', 'Empat', 'Lima', 'Enam', 'Tujuh', 'Delapan', 'Sembilan', 'Sepuluh'];

export const CATEGORIES = [
  {
    id: 'animals', emoji: '🐶', color: '#ff8c42', name: { en: 'Animals', id: 'Hewan' },
    cards: [
      card('dog', '🐶', 'Dog', 'Anjing'),
      card('cat', '🐱', 'Cat', 'Kucing'),
      card('cow', '🐮', 'Cow', 'Sapi'),
      card('chicken', '🐔', 'Chicken', 'Ayam'),
      card('duck', '🦆', 'Duck', 'Bebek'),
      card('sheep', '🐑', 'Sheep', 'Domba'),
      card('goat', '🐐', 'Goat', 'Kambing'),
      card('pig', '🐷', 'Pig', 'Babi'),
      card('horse', '🐴', 'Horse', 'Kuda'),
      card('lion', '🦁', 'Lion', 'Singa'),
      card('tiger', '🐯', 'Tiger', 'Harimau'),
      card('frog', '🐸', 'Frog', 'Katak'),
      card('bird', '🐦', 'Bird', 'Burung'),
      card('owl', '🦉', 'Owl', 'Burung Hantu'),
      card('bee', '🐝', 'Bee', 'Lebah'),
      card('monkey', '🐵', 'Monkey', 'Monyet'),
      card('mouse', '🐭', 'Mouse', 'Tikus'),
      card('snake', '🐍', 'Snake', 'Ular'),
      card('elephant', '🐘', 'Elephant', 'Gajah'),
      card('rabbit', '🐰', 'Rabbit', 'Kelinci'),
      card('bear', '🐻', 'Bear', 'Beruang'),
      card('giraffe', '🦒', 'Giraffe', 'Jerapah'),
      card('zebra', '🦓', 'Zebra', 'Zebra'),
      card('panda', '🐼', 'Panda', 'Panda'),
      card('crocodile', '🐊', 'Crocodile', 'Buaya'),
      card('butterfly', '🦋', 'Butterfly', 'Kupu-kupu'),
      card('ant', '🐜', 'Ant', 'Semut'),
      card('snail', '🐌', 'Snail', 'Siput'),
    ],
  },
  {
    id: 'sea', emoji: '🐳', color: '#3ec1d3', name: { en: 'Sea Animals', id: 'Hewan Laut' },
    cards: [
      card('fish', '🐟', 'Fish', 'Ikan'),
      card('whale', '🐳', 'Whale', 'Paus'),
      card('dolphin', '🐬', 'Dolphin', 'Lumba-lumba'),
      card('shark', '🦈', 'Shark', 'Hiu'),
      card('octopus', '🐙', 'Octopus', 'Gurita'),
      card('crab', '🦀', 'Crab', 'Kepiting'),
      card('turtle', '🐢', 'Turtle', 'Kura-kura'),
      card('shrimp', '🦐', 'Shrimp', 'Udang'),
      card('seal', '🦭', 'Seal', 'Anjing Laut'),
      card('penguin', '🐧', 'Penguin', 'Penguin'),
    ],
  },
  {
    id: 'fruits', emoji: '🍎', color: '#ff5d8f', name: { en: 'Fruits', id: 'Buah' },
    cards: [
      card('apple', '🍎', 'Apple', 'Apel'),
      card('banana', '🍌', 'Banana', 'Pisang'),
      card('orange', '🍊', 'Orange', 'Jeruk'),
      card('grapes', '🍇', 'Grapes', 'Anggur'),
      card('watermelon', '🍉', 'Watermelon', 'Semangka'),
      card('strawberry', '🍓', 'Strawberry', 'Stroberi'),
      card('pineapple', '🍍', 'Pineapple', 'Nanas'),
      card('mango', '🥭', 'Mango', 'Mangga'),
      card('pear', '🍐', 'Pear', 'Pir'),
      card('cherry', '🍒', 'Cherry', 'Ceri'),
      card('coconut', '🥥', 'Coconut', 'Kelapa'),
      card('lemon', '🍋', 'Lemon', 'Lemon'),
      card('kiwi', '🥝', 'Kiwi', 'Kiwi'),
      card('peach', '🍑', 'Peach', 'Persik'),
    ],
  },
  {
    id: 'vegetables', emoji: '🥕', color: '#7bd389', name: { en: 'Vegetables', id: 'Sayuran' },
    cards: [
      card('carrot', '🥕', 'Carrot', 'Wortel'),
      card('corn', '🌽', 'Corn', 'Jagung'),
      card('broccoli', '🥦', 'Broccoli', 'Brokoli'),
      card('tomato', '🍅', 'Tomato', 'Tomat'),
      card('potato', '🥔', 'Potato', 'Kentang'),
      card('cucumber', '🥒', 'Cucumber', 'Timun'),
      card('eggplant', '🍆', 'Eggplant', 'Terong'),
      card('onion', '🧅', 'Onion', 'Bawang Merah'),
      card('garlic', '🧄', 'Garlic', 'Bawang Putih'),
      card('chili', '🌶️', 'Chili', 'Cabai'),
      card('mushroom', '🍄', 'Mushroom', 'Jamur'),
      card('lettuce', '🥬', 'Lettuce', 'Selada'),
    ],
  },
  {
    id: 'food', emoji: '🍞', color: '#ffd23f', name: { en: 'Food & Drinks', id: 'Makanan & Minuman' },
    cards: [
      card('bread', '🍞', 'Bread', 'Roti'),
      card('rice', '🍚', 'Rice', 'Nasi'),
      card('egg', '🥚', 'Egg', 'Telur'),
      card('milk', '🥛', 'Milk', 'Susu'),
      card('water', '💧', 'Water', 'Air'),
      card('noodles', '🍜', 'Noodles', 'Mi'),
      card('soup', '🍲', 'Soup', 'Sup'),
      card('cheese', '🧀', 'Cheese', 'Keju'),
      card('cookie', '🍪', 'Cookie', 'Biskuit'),
      card('cake', '🎂', 'Cake', 'Kue'),
      card('icecream', '🍦', 'Ice Cream', 'Es Krim'),
      card('pizza', '🍕', 'Pizza', 'Piza'),
      card('honey', '🍯', 'Honey', 'Madu'),
      card('juice', '🧃', 'Juice', 'Jus'),
    ],
  },
  {
    id: 'vehicles', emoji: '🚗', color: '#4d96ff', name: { en: 'Vehicles', id: 'Kendaraan' },
    cards: [
      card('car', '🚗', 'Car', 'Mobil'),
      card('bus', '🚌', 'Bus', 'Bus'),
      card('train', '🚂', 'Train', 'Kereta'),
      card('airplane', '✈️', 'Airplane', 'Pesawat'),
      card('boat', '⛵', 'Boat', 'Perahu'),
      card('bicycle', '🚲', 'Bicycle', 'Sepeda'),
      card('motorcycle', '🏍️', 'Motorcycle', 'Sepeda Motor'),
      card('truck', '🚚', 'Truck', 'Truk'),
      { ...card('firetruck', '🚒', 'Fire Truck', 'Mobil Pemadam'), audio: 'vehicles/siren' },
      { ...card('police', '🚓', 'Police Car', 'Mobil Polisi'), audio: 'vehicles/siren' },
      { ...card('ambulance', '🚑', 'Ambulance', 'Ambulans'), audio: 'vehicles/siren' },
      card('helicopter', '🚁', 'Helicopter', 'Helikopter'),
      card('tractor', '🚜', 'Tractor', 'Traktor'),
      card('rocket', '🚀', 'Rocket', 'Roket'),
    ],
  },
  {
    id: 'things', emoji: '⚽', color: '#a66cff', name: { en: 'Things', id: 'Benda' },
    cards: [
      card('ball', '⚽', 'Ball', 'Bola'),
      card('house', '🏠', 'House', 'Rumah'),
      card('book', '📖', 'Book', 'Buku'),
      card('chair', '🪑', 'Chair', 'Kursi'),
      card('bed', '🛏️', 'Bed', 'Kasur'),
      card('door', '🚪', 'Door', 'Pintu'),
      card('lamp', '💡', 'Lamp', 'Lampu'),
      card('clock', '⏰', 'Clock', 'Jam'),
      card('phone', '📱', 'Phone', 'Telepon'),
      card('umbrella', '☂️', 'Umbrella', 'Payung'),
      card('key', '🔑', 'Key', 'Kunci'),
      card('spoon', '🥄', 'Spoon', 'Sendok'),
      card('toothbrush', '🪥', 'Toothbrush', 'Sikat Gigi'),
      card('pencil', '✏️', 'Pencil', 'Pensil'),
      card('scissors', '✂️', 'Scissors', 'Gunting'),
      card('bag', '🎒', 'Bag', 'Tas'),
      card('balloon', '🎈', 'Balloon', 'Balon'),
      card('teddy', '🧸', 'Teddy Bear', 'Boneka'),
    ],
  },
  {
    id: 'clothes', emoji: '👕', color: '#ff7eb6', name: { en: 'Clothes', id: 'Pakaian' },
    cards: [
      card('shirt', '👕', 'Shirt', 'Baju'),
      card('pants', '👖', 'Pants', 'Celana'),
      card('dress', '👗', 'Dress', 'Gaun'),
      card('socks', '🧦', 'Socks', 'Kaus Kaki'),
      card('shoes', '👟', 'Shoes', 'Sepatu'),
      card('hat', '🧢', 'Hat', 'Topi'),
      card('jacket', '🧥', 'Jacket', 'Jaket'),
      card('glasses', '👓', 'Glasses', 'Kacamata'),
      card('gloves', '🧤', 'Gloves', 'Sarung Tangan'),
      card('scarf', '🧣', 'Scarf', 'Syal'),
    ],
  },
  {
    id: 'body', emoji: '👀', color: '#ffb385', name: { en: 'Body', id: 'Tubuh' },
    cards: [
      card('eyes', '👀', 'Eyes', 'Mata'),
      card('nose', '👃', 'Nose', 'Hidung'),
      card('ear', '👂', 'Ear', 'Telinga'),
      card('mouth', '👄', 'Mouth', 'Mulut'),
      card('tongue', '👅', 'Tongue', 'Lidah'),
      card('teeth', '🦷', 'Teeth', 'Gigi'),
      card('hand', '✋', 'Hand', 'Tangan'),
      card('foot', '🦶', 'Foot', 'Kaki'),
      card('arm', '💪', 'Arm', 'Lengan'),
    ],
  },
  {
    id: 'family', emoji: '👨‍👩‍👧', color: '#ff9f9f', name: { en: 'Family', id: 'Keluarga' },
    cards: [
      card('mom', '👩', 'Mom', 'Ibu'),
      card('dad', '👨', 'Dad', 'Ayah'),
      card('baby', '👶', 'Baby', 'Bayi'),
      card('grandma', '👵', 'Grandma', 'Nenek'),
      card('grandpa', '👴', 'Grandpa', 'Kakek'),
      card('boy', '👦', 'Boy', 'Anak Laki-laki'),
      card('girl', '👧', 'Girl', 'Anak Perempuan'),
      card('family', '👨‍👩‍👧', 'Family', 'Keluarga'),
    ],
  },
  {
    id: 'colors', emoji: '🎨', color: '#ffd23f', name: { en: 'Colors', id: 'Warna' },
    cards: [
      ['red', '#ff3b3b', 'Red', 'Merah'],
      ['orange', '#ff8c1a', 'Orange', 'Oranye'],
      ['yellow', '#ffd60a', 'Yellow', 'Kuning'],
      ['green', '#2fbf4a', 'Green', 'Hijau'],
      ['blue', '#2d7bff', 'Blue', 'Biru'],
      ['purple', '#9b4dff', 'Purple', 'Ungu'],
      ['pink', '#ff7eb6', 'Pink', 'Merah Muda'],
      ['brown', '#8b5a2b', 'Brown', 'Cokelat'],
      ['black', '#111111', 'Black', 'Hitam'],
      ['white', '#ffffff', 'White', 'Putih'],
      ['gray', '#8e8e8e', 'Gray', 'Abu-abu'],
    ].map(([id, swatch, en, idn]) => ({ ...card(id, '', en, idn), swatch })),
  },
  {
    id: 'shapes', emoji: '🔺', color: '#4d96ff', name: { en: 'Shapes', id: 'Bentuk' },
    cards: [
      card('circle', '⚫', 'Circle', 'Lingkaran'),
      card('square', '🟦', 'Square', 'Persegi'),
      card('triangle', '🔺', 'Triangle', 'Segitiga'),
      card('star', '⭐', 'Star', 'Bintang'),
      card('heart', '❤️', 'Heart', 'Hati'),
      card('diamond', '🔷', 'Diamond', 'Belah Ketupat'),
      card('crescent', '🌙', 'Crescent', 'Bulan Sabit'),
    ],
  },
  {
    id: 'numbers', emoji: '🔢', color: '#7bd389', name: { en: 'Numbers', id: 'Angka' },
    cards: NUMBERS_EN.map((en, i) => ({
      ...card(`n${i + 1}`, String(i + 1), en, NUMBERS_ID[i]),
      extra: '🟡'.repeat(i + 1),
    })),
  },
  {
    id: 'letters', emoji: '🔤', color: '#a66cff', name: { en: 'ABC', id: 'ABC' },
    cards: [...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map((l) => card(l.toLowerCase(), l, l, l)),
  },
  {
    id: 'nature', emoji: '🌈', color: '#3ec1d3', name: { en: 'Nature', id: 'Alam' },
    cards: [
      card('sun', '☀️', 'Sun', 'Matahari'),
      card('moon', '🌙', 'Moon', 'Bulan'),
      card('star', '⭐', 'Star', 'Bintang'),
      card('cloud', '☁️', 'Cloud', 'Awan'),
      card('rain', '🌧️', 'Rain', 'Hujan'),
      card('rainbow', '🌈', 'Rainbow', 'Pelangi'),
      card('lightning', '⚡', 'Lightning', 'Petir'),
      card('snow', '❄️', 'Snow', 'Salju'),
      card('tree', '🌳', 'Tree', 'Pohon'),
      card('flower', '🌸', 'Flower', 'Bunga'),
      card('leaf', '🍃', 'Leaf', 'Daun'),
      card('mountain', '⛰️', 'Mountain', 'Gunung'),
      card('sea', '🌊', 'Sea', 'Laut'),
      card('fire', '🔥', 'Fire', 'Api'),
    ],
  },
];
