"""Generate the app's voice clips with open neural TTS models (runs offline).

    pip install sherpa-onnx soundfile numpy      # plus ffmpeg on PATH
    node tools/voice/phrases.mjs                 # collect phrases -> phrases.json
    python tools/voice/generate.py --kokoro DIR --piper-id DIR [--en-speaker 0]

Models (from https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models):
  English:    kokoro-multi-lang-v1_1       (Kokoro, Apache-2.0)
  Indonesian: vits-piper-id_ID-news_tts-medium  (Piper)

Writes voice/<lang>/<slug>.mp3 and voice/manifest.js. Existing clips are kept
unless --force is given, so re-running only renders new phrases.
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile

import numpy as np
import sherpa_onnx as so
import soundfile as sf

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Post-processing: trim silence, make it a touch brighter/livelier, even out loudness.
TRIM = ("silenceremove=start_periods=1:start_threshold=-55dB:start_silence=0.06,"
        "areverse,silenceremove=start_periods=1:start_threshold=-55dB:start_silence=0.12,areverse")
FILTERS = {
    "en": f"{TRIM},loudnorm=I=-16:TP=-1.5",
    # The Indonesian voice is a newsreader; raise the pitch a little so it sounds friendlier.
    "id": f"{TRIM},rubberband=pitch=1.12:tempo=1.04,loudnorm=I=-16:TP=-1.5",
}


def kokoro(d, speaker, speed):
    cfg = so.OfflineTtsConfig(model=so.OfflineTtsModelConfig(
        kokoro=so.OfflineTtsKokoroModelConfig(
            model=f"{d}/model.onnx", voices=f"{d}/voices.bin", tokens=f"{d}/tokens.txt",
            data_dir=f"{d}/espeak-ng-data", dict_dir=f"{d}/dict",
            lexicon=f"{d}/lexicon-us-en.txt,{d}/lexicon-zh.txt"),
        num_threads=4))
    tts = so.OfflineTts(cfg)
    return lambda text: tts.generate(text, sid=speaker, speed=speed)


def piper(d, speed):
    onnx = next(f for f in os.listdir(d) if f.endswith(".onnx"))
    cfg = so.OfflineTtsConfig(model=so.OfflineTtsModelConfig(
        vits=so.OfflineTtsVitsModelConfig(
            model=f"{d}/{onnx}", tokens=f"{d}/tokens.txt", data_dir=f"{d}/espeak-ng-data",
            noise_scale=0.8, noise_scale_w=0.9, length_scale=1.0 / speed),
        num_threads=4))
    tts = so.OfflineTts(cfg)
    return lambda text: tts.generate(text, sid=0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--kokoro", required=True)
    ap.add_argument("--piper-id", required=True)
    ap.add_argument("--en-speaker", type=int, default=0)
    ap.add_argument("--ffmpeg", default="ffmpeg")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--only", help="comma-separated keys to (re)render")
    args = ap.parse_args()

    phrases = json.load(open(os.path.join(ROOT, "tools/voice/phrases.json"), encoding="utf-8"))
    engines = {
        "en": kokoro(args.kokoro, args.en_speaker, speed=0.9),
        "id": piper(args.piper_id, speed=0.95),
    }
    only = set(args.only.split(",")) if args.only else None
    manifest = {"en": [], "id": []}

    with tempfile.TemporaryDirectory() as tmp:
        for i, p in enumerate(phrases):
            lang, key, text = p["lang"], p["key"], p["text"]
            out = os.path.join(ROOT, "voice", lang, f"{key}.mp3")
            manifest[lang].append(key)
            if os.path.exists(out) and not args.force and not (only and key in only):
                continue
            if only and key not in only:
                continue
            audio = engines[lang](text)
            wav = os.path.join(tmp, "a.wav")
            sf.write(wav, np.asarray(audio.samples), audio.sample_rate)
            os.makedirs(os.path.dirname(out), exist_ok=True)
            subprocess.run([args.ffmpeg, "-loglevel", "error", "-y", "-i", wav, "-af", FILTERS[lang],
                            "-ac", "1", "-ar", "24000", "-b:a", "48k", out], check=True)
            print(f"[{i + 1}/{len(phrases)}] {lang} {key}: {text}", file=sys.stderr)

    with open(os.path.join(ROOT, "voice", "manifest.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/voice/generate.py - lists the recorded voice clips.\n")
        f.write("export default " + json.dumps(manifest, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    main()
